/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_test_TestParameters */

#ifndef _Included_org_test_TestParameters
#define _Included_org_test_TestParameters
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_test_TestParameters
 * Method:    func
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_org_test_TestParameters_func
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
